# Generated by Django 5.2.6 on 2025-09-23 11:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.RemoveField(
            model_name='estadistica',
            name='errores_totales',
        ),
        migrations.RemoveField(
            model_name='estadistica',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='estadistica',
            name='registros_totales',
        ),
        migrations.RemoveField(
            model_name='iaanalisis',
            name='confianza',
        ),
        migrations.RemoveField(
            model_name='iaanalisis',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='iaanalisis',
            name='tipo_error_predominante',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='puntaje',
        ),
        migrations.AddField(
            model_name='estadistica',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='estadistica',
            name='mejoras',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='iaanalisis',
            name='fecha_analisis',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='iaanalisis',
            name='patrones_detectados',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='registro',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('supervisor', 'Supervisor'), ('empleado', 'Empleado')], default='empleado', max_length=20),
        ),
    ]
