# Generated by Django 5.2.6 on 2025-09-23 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_usuario_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_id', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField()),
                ('ventana_activa', models.CharField(max_length=200)),
                ('procesos_activos', models.JSONField(default=list)),
                ('carga_sistema', models.JSONField(default=dict)),
                ('productividad', models.CharField(choices=[('productive', 'Productivo'), ('unproductive', 'No Productivo'), ('gaming', 'Jugando'), ('neutral', 'Neutral')], max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Actividad de Usuario',
                'verbose_name_plural': 'Actividades de Usuarios',
                'ordering': ['-timestamp'],
            },
        ),
    ]
